version: "3.3"

volumes:
  file_data:
  static:
  pg_data:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build:
      context: ./file_uploader
      dockerfile: Dockerfile
    env_file: .env
    command: ["/app/entrypoint_uploader.sh"]
    volumes:
      - file_data:/app/media/
      - static:/backend_static/static/
    depends_on:
      - db

  redis:
    image: redis:7
    command: --port 6379
    expose:
      - 6379
    env_file: .env
    depends_on:
      - web

  celery:
    build:
      context: ./file_uploader
    command: ["/app/entrypoint_worker.sh", "celery"]
    env_file: .env
    volumes:
      - file_data:/app/media/
    depends_on:
      - web
      - redis
      - db

  flower:
    build:
      context: ./file_uploader
    command: ["/app/entrypoint_worker.sh", "flower"]
    env_file: .env
    volumes:
      - file_data:/app/media/
    depends_on:
      - web
      - redis
      - db
      - celery
    expose:
      - 5555
    ports:
      - 5555:5555

  gateway:
    build:
      context: ./gateway/
      dockerfile: Dockerfile
    ports:
      - 9000:80
    volumes:
      - static:/static/static/
      - file_data:/media/
    depends_on:
      - web
      - flower